#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 27 13:39:15 2019

@author: mdl-admin
"""

Question:
    When should I use msecDelay and pumpDelay?
        pylink.msecDelay(100)
        pylink.pumpDelay(100)
    
    Do I need to set tk.setOfflineMode() after every trial?
    
    When do I use pylink.endRealTimeMode()?